/* ═══════════════════════════════════════════════════════
   api/send-report.js — Vercel serverless: email zone report
   Requires environment variables:
     GMAIL_USER          your Gmail address
     GMAIL_APP_PASSWORD  16-char Gmail App Password (not your login password)
     REPORT_TO           recipient address (default: GMAIL_USER)
   ═══════════════════════════════════════════════════════ */

const nodemailer = require('nodemailer');

module.exports = async function handler(req, res) {
  // CORS for same-origin Vercel deployments
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { pdf, jpeg, jpegs, regionName, weekDate } = req.body || {};

  if (!pdf && !jpeg && !jpegs?.length) {
    return res.status(400).json({ error: 'No report data provided' });
  }

  const { GMAIL_USER, GMAIL_APP_PASSWORD, REPORT_TO } = process.env;

  if (!GMAIL_USER || !GMAIL_APP_PASSWORD) {
    return res.status(500).json({
      error: 'Email not configured. Add GMAIL_USER and GMAIL_APP_PASSWORD in Vercel environment variables.',
    });
  }

  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: GMAIL_USER,
      pass: GMAIL_APP_PASSWORD,
    },
  });

  const recipient = REPORT_TO || GMAIL_USER;
  const subject   = `${regionName} · Filbertworm Trap Report · ${weekDate}`;
  const safeZone  = (regionName || 'zone').replace(/[^a-z0-9_\-]/gi, '_');

  const attachments = [];
  if (pdf) {
    attachments.push({
      filename:    `${safeZone}_${weekDate}_report.pdf`,
      content:     Buffer.from(pdf, 'base64'),
      contentType: 'application/pdf',
    });
  }
  if (jpegs && jpegs.length) {
    for (const { base64, filename } of jpegs) {
      attachments.push({
        filename:    filename || `${safeZone}_${weekDate}_report.jpg`,
        content:     Buffer.from(base64, 'base64'),
        contentType: 'image/jpeg',
      });
    }
  } else if (jpeg) {
    attachments.push({
      filename:    `${safeZone}_${weekDate}_report.jpg`,
      content:     Buffer.from(jpeg, 'base64'),
      contentType: 'image/jpeg',
    });
  }

  try {
    await transporter.sendMail({
      from: `Valley Ag Monitoring <${GMAIL_USER}>`,
      to:   recipient,
      subject,
      html: `
        <div style="font-family:system-ui,sans-serif;max-width:560px;margin:0 auto;color:#1a2e1f">
          <div style="background:#1a3d23;padding:24px 32px;border-radius:12px 12px 0 0">
            <h2 style="color:white;margin:0;font-size:1.15rem">${subject}</h2>
          </div>
          <div style="background:#f7faf7;padding:24px 32px;border-radius:0 0 12px 12px;border:1px solid #d8e9db">
            <p style="margin:0 0 12px">Please find the weekly filbertworm trap reports attached — one overall summary and one per zone.</p>
            <ul style="margin:0 0 16px;padding-left:20px;color:#3d5444;font-size:0.92rem">
              <li><strong>Overall</strong> — all zones, season chart, and degree day model</li>
              <li><strong>Zone 1–5</strong> — individual zone maps with this-week counts</li>
            </ul>
            <p style="margin:0;font-size:0.82rem;color:#6b7f72">
              Generated by Valley Agronomics Donald Trap Monitoring System.<br>
              Confidential — for internal use only.
            </p>
          </div>
        </div>
      `,
      attachments,
    });

    return res.status(200).json({ success: true, recipient });
  } catch (err) {
    console.error('Email send error:', err.message);
    return res.status(500).json({ error: err.message });
  }
};
